"""add documents, document_approvals, fats tables

Revision ID: 0ab0f4f81754
Revises: e6699f9c6dc4
Create Date: 2026-05-26 17:49:20.793768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab0f4f81754'
down_revision: Union[str, Sequence[str], None] = 'e6699f9c6dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fats',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discipline_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('site_engineer_id', sa.UUID(), nullable=True),
    sa.Column('qaqc_engineer_id', sa.UUID(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_approver_order', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_note', sa.String(length=255), nullable=True),
    sa.Column('is_milestone_delivery', sa.Boolean(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('sub_activity_id', sa.UUID(), nullable=True),
    sa.Column('is_milestone_activity', sa.Boolean(), nullable=True),
    sa.Column('test_id', sa.UUID(), nullable=True),
    sa.Column('is_milestone_test', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['qaqc_engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_activity_id'], ['sub_activities.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_number'), 'documents', ['number'], unique=False)
    op.create_table('fat_assets',
    sa.Column('fat_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fat_id'], ['fats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fat_id', 'asset_id')
    )
    op.create_table('document_approvals',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('approver_order', sa.Integer(), nullable=False),
    sa.Column('project_approver_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_approver_id'], ['project_approvers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['approval_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_assets',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_assets')
    op.drop_table('document_approvals')
    op.drop_table('fat_assets')
    op.drop_index(op.f('ix_documents_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('fats')
    # ### end Alembic commands ###
