"""add_document_sub_activities_table

Revision ID: 0db21f0c4997
Revises: 428b52a8cfaa
Create Date: 2026-05-27 14:08:14.811077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db21f0c4997'
down_revision: Union[str, Sequence[str], None] = '428b52a8cfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sub_activities',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('sub_activity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_activity_id'], ['sub_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'sub_activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_sub_activities')
    # ### end Alembic commands ###
