"""add cell_id to project_header_images

Revision ID: 1688fbd75c36
Revises: a42093b7bd93
Create Date: 2026-05-26 21:52:31.823229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1688fbd75c36'
down_revision: Union[str, Sequence[str], None] = 'a42093b7bd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_header_images', sa.Column('cell_id', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('uq_project_header_image'), 'project_header_images', type_='unique')
    op.create_unique_constraint('uq_project_header_cell', 'project_header_images', ['project_id', 'cell_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_header_cell', 'project_header_images', type_='unique')
    op.create_unique_constraint(op.f('uq_project_header_image'), 'project_header_images', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('project_header_images', 'cell_id')
    # ### end Alembic commands ###
