"""add_signature_booleans_to_documents

Revision ID: 2cb7aaee968a
Revises: ed7ed8442428
Create Date: 2026-05-27 13:51:26.665475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb7aaee968a'
down_revision: Union[str, Sequence[str], None] = 'ed7ed8442428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('site_engineer_signed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('qaqc_engineer_signed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'qaqc_engineer_signed')
    op.drop_column('documents', 'site_engineer_signed')
    # ### end Alembic commands ###
