"""add_external_code_to_projects

Revision ID: 428b52a8cfaa
Revises: 2cb7aaee968a
Create Date: 2026-05-27 14:02:37.276097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428b52a8cfaa'
down_revision: Union[str, Sequence[str], None] = '2cb7aaee968a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('external_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'external_code')
    # ### end Alembic commands ###
