"""add_wir_fields_and_signature_font

Revision ID: 64093a573b15
Revises: 6d9375c4aa87
Create Date: 2026-05-27 11:33:00.987291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64093a573b15'
down_revision: Union[str, Sequence[str], None] = '6d9375c4aa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('floor_level', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('rams_ref', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('drawing_ref', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('signature_font', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature_font')
    op.drop_column('documents', 'inspection_date')
    op.drop_column('documents', 'drawing_ref')
    op.drop_column('documents', 'rams_ref')
    op.drop_column('documents', 'floor_level')
    op.drop_column('documents', 'location')
    # ### end Alembic commands ###
