"""replace_template_builder_with_doc_templates

Revision ID: 6d9375c4aa87
Revises: 8a49cae8d095
Create Date: 2026-05-27 10:51:16.212158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d9375c4aa87'
down_revision: Union[str, Sequence[str], None] = '8a49cae8d095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_templates',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_templates_doc_type'), 'doc_templates', ['doc_type'], unique=False)
    op.create_index(op.f('ix_doc_templates_project_id'), 'doc_templates', ['project_id'], unique=False)
    op.drop_table('project_header_images')
    op.drop_index(op.f('ix_document_templates_doc_type'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('document_templates_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_templates_pkey')),
    sa.UniqueConstraint('project_id', 'doc_type', name=op.f('uq_template_project_doctype'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_templates_doc_type'), 'document_templates', ['doc_type'], unique=False)
    op.create_table('project_header_images',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cell_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_header_images_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_header_images_pkey')),
    sa.UniqueConstraint('project_id', 'cell_id', name=op.f('uq_project_header_cell'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_doc_templates_doc_type'), table_name='doc_templates')
    op.drop_table('doc_templates')
    # ### end Alembic commands ###
