"""add document_templates and reference_number_configs

Revision ID: d58d31eeccc1
Revises: 0ab0f4f81754
Create Date: 2026-05-26 19:12:01.601679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd58d31eeccc1'
down_revision: Union[str, Sequence[str], None] = '0ab0f4f81754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'doc_type', name='uq_template_project_doctype')
    )
    op.create_index(op.f('ix_document_templates_doc_type'), 'document_templates', ['doc_type'], unique=False)
    op.create_table('reference_number_configs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('contractor_code', sa.String(length=50), nullable=False),
    sa.Column('serial_start', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'doc_type', name='uq_refnum_project_doctype')
    )
    op.create_index(op.f('ix_reference_number_configs_doc_type'), 'reference_number_configs', ['doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_number_configs_doc_type'), table_name='reference_number_configs')
    op.drop_table('reference_number_configs')
    op.drop_index(op.f('ix_document_templates_doc_type'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
