"""add unique constraints to code fields

Revision ID: e6699f9c6dc4
Revises: 38f56648d527
Create Date: 2026-05-26 15:24:57.024456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6699f9c6dc4'
down_revision: Union[str, Sequence[str], None] = '38f56648d527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_activity_code_service', 'activities', ['code', 'service_id'])
    op.create_unique_constraint('uq_contractor_code_project', 'contractors', ['code', 'project_id'])
    op.create_unique_constraint('uq_discipline_code_project', 'disciplines', ['code', 'project_id'])
    op.create_unique_constraint('uq_service_code_discipline', 'services', ['code', 'discipline_id'])
    op.create_unique_constraint('uq_subactivity_code_activity', 'sub_activities', ['code', 'activity_id'])
    op.create_unique_constraint('uq_system_code_project', 'systems', ['code', 'project_id'])
    op.create_unique_constraint('uq_test_code_project', 'tests', ['code', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_test_code_project', 'tests', type_='unique')
    op.drop_constraint('uq_system_code_project', 'systems', type_='unique')
    op.drop_constraint('uq_subactivity_code_activity', 'sub_activities', type_='unique')
    op.drop_constraint('uq_service_code_discipline', 'services', type_='unique')
    op.drop_constraint('uq_discipline_code_project', 'disciplines', type_='unique')
    op.drop_constraint('uq_contractor_code_project', 'contractors', type_='unique')
    op.drop_constraint('uq_activity_code_service', 'activities', type_='unique')
    # ### end Alembic commands ###
