"""add_signature_text_to_users

Revision ID: f67e0f7aca84
Revises: 64093a573b15
Create Date: 2026-05-27 11:56:39.031634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67e0f7aca84'
down_revision: Union[str, Sequence[str], None] = '64093a573b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signature_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature_text')
    # ### end Alembic commands ###
